apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
  namespace: microservices-demo
  annotations:
    checkov.io/skip1: CKV_SECRET_4=This is the source definition of the secret, credentials are required.
type: Opaque
stringData:
  database-url: "postgres://okteto:okteto@postgresql:5432/votes"
