# Default values for infrastructure.
postgresql:
  enabled: true
  auth:
    database: votes
    username: okteto
    password: okteto
kafka:
  enabled: true
  replicaCount: 1
  zookeeper:
    enabled: true
  persistence:
    enabled: true
  externalZookeeper:
    enabled: false
